name: lando-wp-phpunit
recipe: wordpress
proxy:
  nginx: # This could be anything you like as long as you point the domain to 127.0.0.1 in your /etc/hosts file
    - lando-wp-phpunit.lndo.site
  pma: # Use the below url to access PHPMyAdmin :-)
    - pma.lando-wp-phpunit.lndo.site
  mailhog: # Use mail url for a way to view emails send from your local dev instance
    - mail.lando-wp-phpunit.lndo.site
config:
  env: dev
  php: '7.3'
  via: nginx
  webroot: public_html
  database: mariadb
  xdebug: true
services:
  appserver:
    composer:
      phpunit/phpunit: "^7.0"
    build_as_root:
      - apt-get update -y
      - apt-get install subversion -y
    build:
      - composer install
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  test:
    description: "Run ALL THE TESTS"
    cmd:
      - appserver: phpunit
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
